### ISSUE TITLE
The devstack script for mongodb is failing

### ISSUE THREAD

**Issue by cassand** [PowerSpikeGG/PowerSpikeGG#20]
It seems to be related to a missing module for python (lru_cache)

>cassan@cassan-Latitude-E5540:~/Documents/projects/PowerSpikeGG$ ./powerspikegg/rawdata/tools/devstack.sh 
INFO: Found 2 targets...
INFO: Elapsed time: 0.092s, Critical Path: 0.00s
2017-02-11T20:07:13.480+0100 I CONTROL  [initandlisten] MongoDB starting : pid=30310 port=27017 dbpath=/tmp/tmp.d9i5T4idAZ/data 64-bit host=cassan-Latitude-E5540
2017-02-11T20:07:13.480+0100 I CONTROL  [initandlisten] db version v3.4.1
2017-02-11T20:07:13.480+0100 I CONTROL  [initandlisten] git version: 5e103c4f5583e2566a45d740225dc250baacfbd7
2017-02-11T20:07:13.480+0100 I CONTROL  [initandlisten] allocator: tcmalloc
2017-02-11T20:07:13.480+0100 I CONTROL  [initandlisten] modules: none
2017-02-11T20:07:13.480+0100 I CONTROL  [initandlisten] build environment:
2017-02-11T20:07:13.480+0100 I CONTROL  [initandlisten]     distarch: x86_64
2017-02-11T20:07:13.480+0100 I CONTROL  [initandlisten]     target_arch: x86_64
2017-02-11T20:07:13.480+0100 I CONTROL  [initandlisten] options: { processManagement: { pidFilePath: "/tmp/tmp.d9i5T4idAZ/pid" }, storage: { dbPath: "/tmp/tmp.d9i5T4idAZ/data" } }
2017-02-11T20:07:13.505+0100 I STORAGE  [initandlisten] 
2017-02-11T20:07:13.505+0100 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-02-11T20:07:13.505+0100 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-02-11T20:07:13.505+0100 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3432M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-02-11T20:07:13.608+0100 I CONTROL  [initandlisten] 
2017-02-11T20:07:13.608+0100 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-02-11T20:07:13.608+0100 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-02-11T20:07:13.608+0100 I CONTROL  [initandlisten] 
2017-02-11T20:07:13.608+0100 I CONTROL  [initandlisten] 
2017-02-11T20:07:13.609+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-02-11T20:07:13.609+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-02-11T20:07:13.609+0100 I CONTROL  [initandlisten] 
2017-02-11T20:07:13.628+0100 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/tmp/tmp.d9i5T4idAZ/data/diagnostic.data'
2017-02-11T20:07:13.654+0100 I INDEX    [initandlisten] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-02-11T20:07:13.654+0100 I INDEX    [initandlisten] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-02-11T20:07:13.655+0100 I INDEX    [initandlisten] build index done.  scanned 0 total records. 0 secs
2017-02-11T20:07:13.655+0100 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.4
2017-02-11T20:07:13.655+0100 I NETWORK  [thread1] waiting for connections on port 27017
Traceback (most recent call last):
  File "/home/cassan/Documents/projects/PowerSpikeGG/bazel-bin/powerspikegg/rawdata/fetcher/server.runfiles/org_powerspikegg/powerspikegg/rawdata/fetcher/server.py", line 14, in <module>
    from powerspikegg.rawdata.fetcher import converter
  File "/home/cassan/Documents/projects/PowerSpikeGG/bazel-bin/powerspikegg/rawdata/fetcher/server.runfiles/org_powerspikegg/powerspikegg/rawdata/fetcher/converter.py", line 1, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache
 

Installing the module lru_cache locally does not solve the problem, it might be related to bazel

**Comment by FunkySayu** [comment]
A quick and dirty fix for that is to install the lru_cache as following:

    pip install --user lru_cache

I'll install it into the bazel stack in a fix

EDIT: Actually I lied, it looks like lru_cache is only for python>=3.2. I think I can remove it for now.
